[package]
name = "basic2wasm"
version = "0.1.0"
authors = ["Yiran Sheng <shengyiran@gmail.com>"]
edition = "2018"

[dependencies]
indoc = "0.2"
binaryen = "0.5.0"
slotmap = "0.3.0"
either = "1.5.0"
rustc-hash = "1.0.1"
basic_rs = { path = "../" }
