[package]
name = "basic2js"
version = "0.1.0"
authors = ["Yiran Sheng <shengyiran@gmail.com>"]
edition = "2018"

[dependencies]
indoc = "0.2"
structopt = "0.2.13"
toml = "0.4.10"
basic_rs = { path = "../" }
